import localFont from "next/font/local";
import type { Metadata } from "next";
import { Footer, Nav } from "./components/layout";
import "./globals.css";
import { Providers } from "./providers";

const rubikSans = localFont({
  src: "./fonts/Rubik-VariableFont_wght.ttf",
  variable: "--font-rubik",
  weight: "300 900",
});

export const metadata: Metadata = {
  title: "GRILL HOUSE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rubikSans.variable} antialiased`}>
        <Providers>
          <>
            <Nav />
            {children}
            <Footer />
          </>
        </Providers>
      </body>
    </html>
  );
}
