import type { Metadata } from "next";
import localFont from "next/font/local";
import Image from "next/image";

import "./globals.css";
import { Container } from "./components";
import Link from "next/link";
import MyHamburger from "./components/layout/myHamburger";

const rubikSans = localFont({
  src: "./fonts/Rubik-VariableFont_wght.ttf",
  variable: "--font-rubik",
  weight: "300 900",
});

export const metadata: Metadata = {
  title: "GRILL HOUSE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rubikSans.variable} antialiased`}>
        <nav className="xl:border-b border-[#F3F3F7]">
          <Container>
            <div className="h-[68px] flex items-center text-sm leading-[16.6px] justify-between">
              <div className="xl:hidden block w-[103px]">
                <Image
                  src="/logo.png"
                  alt="grill house"
                  width={103}
                  height={38}
                  className="w-full"
                />
              </div>
              <ul className="xl:flex hidden gap-6 items-center">
                <li className="hover:text-[#706e6e] transition-colors duration-150">
                  <Link href="/">Главная</Link>
                </li>
                <li className="hover:text-[#706e6e] transition-colors duration-150">
                  <Link href="/about_us">О нас</Link>
                </li>
                <li className="hover:text-[#706e6e] transition-colors duration-150">
                  <Link href="/contacts">Контакты</Link>
                </li>
              </ul>
              <div className="xl:flex hidden gap-6 items-center">
                <Link
                  href="tel:+79289876543"
                  className="font-medium hover:text-[#706e6e] transition-colors duration-150"
                >
                  + 7 (928) 987-65-43
                </Link>
                <div>c 09:00 до 22:00</div>
              </div>

              <MyHamburger />
            </div>
          </Container>
        </nav>
        {children}
      </body>
    </html>
  );
}
